environment:
  matrix:
    - PY: "3.6"

install:
  #######################
  ## install miniconda ##
  - "C:\\Python36-x64\\Scripts\\pip.exe install ioamdoit"
  - "C:\\Python36-x64\\Scripts\\doit.exe install_miniconda"
  - "SET PATH=%HOME%\\miniconda;%HOME%\\miniconda\\Scripts;%PATH%"
  #######################
  - python --version
  - where python
  - pip --version
  - where pip
  - echo $PY
  - pip install ioamdoit
  - doit create_env --python=$PY
  - activate test-environment
  - doit install_dependencies
  - conda list && conda env export
  - python setup.pt develop --no-deps

build: off

test_script:
  - doit all_tests

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
      - aramco@continuum.flowdock.com
    on_build_status_changed: true
    on_build_failure: true
    on_build_success: false

artifacts:
  - path: 'examples\*.html'
    name: examples
