git:
  depth: 100

language: generic

os:
  - linux

sudo: false

env:
  global:
    secure: qDzvmjcR6eLAmHx0ziN3Y5M8h65+OM+eBNERQsC3WSkeaD45rEE6a8w59dBdUzZBTLKO2RP8pKlgzxBZGOBlnLbTyN4RD/q2dA+gm5c0SDWWT4kVCiogJVsrzyRHVgMDmqDu56HPbQzhsW+5Qh2JKjVkkI7GwvGZRFB9WKQC8yjW/RfLvQ7bzX6jXbaHDYg9dywjI5u7da7HZKXyt/6nhebdaI19RdQHuESUqTADFEgdCKdzrNC+NqbJ8SUnNBBmkb1ZqoQ3/p1/Z/+uDi/2ThozE7Lz6gl8HtxVRnBiwNCDvZRE8uTB79+FlW0FJCVZ7qGO8jVWlVqy+WEEFh/6s9RP2PLd73CmItfF7BzSdxdurOYfnizboqCideSasDQK7XdeDiX4fPrgqbeesn8+XJ9vhxRAmpsNdZIU+2pivgviJwUZUwKwgzt3hf23ld9GpJg60wCfQRT8hiZc3/XsUPrzDjci7hwrRESqobPcuWk6xsFPTvJsTeOSLejP1wDOGAhufLTQIys26BSwHiaj6aI4RPK3Y4sy644m4IOfVvi3d+YfyN2Q5NO7QIwk5PjQBUEdwcIi3lAk2eAIjJamlDYFCRrnwuEoFinuFlUjtqpkuVTLgonTbk9KkIYnXeP3wYERrt4uOJtxDRCojBC0FI5rDbkhC3wP8Wef4EToQ+s=

stages:
  - test
  - doc
  - name: anaconda_deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - &tests
      stage: test
      env: PYTHON_VERSION="2.7"
      before_install:
      - easy_install --user doit==0.29.0
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          ~/Library/Python/2.7/bin/doit install_miniconda;
        else
          ~/.local/bin/doit install_miniconda;
        fi
      - rm -f .doit.db
      - export PATH="$HOME/miniconda/bin:$PATH"
      - pip install doit
      - doit create_env --python=$PYTHON_VERSION
      - source activate test-environment
      install:
      - doit install_test_dependencies
      - conda list && conda env export
      - python setup.py develop --no-deps
      script:
      - doit lint
      - doit tests

    - <<: *tests
      env: PYTHON_VERSION="3.6"

    - <<: *tests
      stage: doc
      env: PYTHON_VERSION="3.6"
      install:
      # TODO: could (build and) use conda package; to be cleaned up
      # once auto versioning/package building is finalized      
      - doit --verbosity 2 install_doc_dependencies
      - conda list && conda env export      
      - python setup.py develop --no-deps
      script:
      - doit docs
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./doc/_build/html
          on:
            # TODO: depending on what we do for auto versioning/packaging,
            # should make this deploy somewhere for PRs etc, and only to the
            # main site on specific tag format.
            tags: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./doc/_build/html
          repo: ioam-docs/parambokeh-master

    - <<: *tests 
      stage: anaconda_deploy
      env: PYTHON_VERSION="3.6"
      install:
      - source deactivate
      - conda install -q -y "conda-build=3.0.25" anaconda-client
      script:
      - conda build conda.recipe
      - anaconda -t $CONDA_UPLOAD_TOKEN upload --force -u cball $HOME/miniconda/conda-bld/noarch/parambokeh*.tar.bz2
