package:
  name: parambokeh
  version: 0.0.1

source:
  path: .

extra:
  channels:
    - ioam
    - conda-forge

requirements:
  build:
    - python
    - setuptools
    - param >=1.5.1
  run:
    - python
    - bokeh >=0.12.5
    - param >=1.5.1

test:
  imports:
    - parambokeh

about:
  home: http://github.com/ioam/parambokeh
  summary: Generate bokeh widgets from Parameterized objects on bokeh server
  license: BSD
