package:
  name: parambokeh
  version: 0.2.1

source:
  path: .

requirements:
  build:
    - python
  run:
    - python
    - param
    - bokeh

test:
  imports:
    - parambokeh

about:
  home: https://github.com/ioam/parambokeh
  summary: ParamBokeh provides an easy way to generate a UI for param based classes in the notebook or on bokeh server.
  license: BSD 3-Clause
