package:
  name: parambokeh
  version: {{ os.environ.get("VERSIONHACK") }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
    - param
    - bokeh >=0.12.10

test:
  requires:
    - holoviews >=1.9.0
    - pandas
    - notebook
    - flake8
    - pyparsing
    - pytest
  imports:
    - parambokeh

about:
  home: https://github.com/ioam/parambokeh
  summary: ParamBokeh provides an easy way to generate a UI for param based classes in the notebook or on bokeh server.
  license: BSD 3-Clause
